name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test-esm:
    name: Test ESM & CJS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20, 22, 24]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: run test ESM
      run: |
        npm run updatedb
        npx jasmine spec/*.mjs
    - name: run test CJS
      run: |
        npm run cjs
        npx jasmine spec/*.cjs
